# Use the official Playwright Docker image
FROM mcr.microsoft.com/playwright:v1.49.0-noble

ARG BASE_URL

ENV BASE_URL=$BASE_URL

# Set the working directory inside the container
WORKDIR /app

COPY playwright.config.ts /app/

RUN npm init -y
RUN npm install @playwright/test

# Install Playwright browsers
RUN npx playwright install --with-deps

# Default command for Playwright
CMD ["npx", "playwright", "test"]