name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
        env:
          BASE: alpinecss
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./apps/docs/dist
          branch: gh-pages
          clean-exclude: pr-preview
          force: false