name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Install Pa11y globally
        run: npm install -g pa11y
      - name: Accessibility testing
        run: npm run test:a11y:ci

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "BASE=alpinecss/pr-preview/pr-${{ github.event.number }}" >> "$GITHUB_ENV"
      - run: echo "BASE is $BASE"
        env:
          BASE: ${{ env.BASE }}
      - run: npm ci
      - run: npm run build
        env:
          BASE: ${{ env.BASE }}
        if: github.event.action != 'closed'
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./apps/docs/dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

  visual-regression:
    needs: deploy-preview
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-noble
#      options: --user 1001
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - run: echo "BASE_URL=https://andreas-ku.github.io/alpinecss/pr-preview/pr-${{ github.event.number }}" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run the tests
        run: npx playwright test
        env:
          BASE_URL: ${{ env.BASE_URL }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30