name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - closed

jobs:
  remove-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./apps/docs/dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
