name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "BASE=alpinecss/pr-preview/pr-${{ github.event.number }}" >> "$GITHUB_ENV"
      - run: npm ci
      - name: Check code formatting
        run: npm run format:check
      - run: npm run build
        env:
          BASE: ${{ env.BASE }}
      - run: npm install -g pa11y
      - run: npm run test:a11y:ci
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: .

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: .
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./apps/docs/dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

#  visual-regression:
#    runs-on: ubuntu-latest
#    container:
#      image: mcr.microsoft.com/playwright:v1.49.0-noble
##      options: --user 1001
#    steps:
#      - name: Checkout your repository using git
#        uses: actions/checkout@v4
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
#
#      - name: Run the tests
#        run: npx playwright test
#
#      - uses: actions/upload-artifact@v4
#        if: ${{ !cancelled() }}
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30